import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const clientSource = await readFile(new URL('../tavern-plugin/lib/client.js', import.meta.url), 'utf8')
const clientCss = await readFile(new URL('../tavern-plugin/lib/client-assets/tavern.css', import.meta.url), 'utf8')
const serverSource = await readFile(new URL('../tavern-plugin/lib/index.js', import.meta.url), 'utf8')
const orchestrationStrategiesSource = await readFile(new URL('../tavern-plugin/lib/domain/foreground-orchestration-strategies.js', import.meta.url), 'utf8')
const scriptHostAdapterSource = await readFile(new URL('../tavern-plugin/lib/domain/tavern-script-host-adapter.js', import.meta.url), 'utf8')
const presetConversionSource = await readFile(new URL('../tavern-plugin/lib/domain/preset-conversion-preview.js', import.meta.url), 'utf8')
const turnOrchestrationSource = await readFile(new URL('../tavern-plugin/lib/domain/turn-orchestration.js', import.meta.url), 'utf8')
const remoteClientSource = await readFile(new URL('../tavern-plugin/packages/dsh-tavern-remote/src/client.ts', import.meta.url), 'utf8')

function between(source, start, end) {
  const from = source.indexOf(start)
  const to = source.indexOf(end, from)
  assert.notEqual(from, -1, `missing start marker: ${start}`)
  assert.notEqual(to, -1, `missing end marker: ${end}`)
  return source.slice(from, to)
}

test('打开游玩会话持久记录最近打开时间，并用同一字段排序与展示', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const open = between(sidebar, 'async function openSessionWhenReady', 'async function finishPendingOpen')

  assert.match(open, /call\("markConversationOpened", \{ sessionId: sessionId \}\)/)
  assert.ok(open.indexOf('sessionListRecoveryRef.current.open(sessionId)') < open.indexOf('call("markConversationOpened"'))
  assert.match(serverSource, /case 'markConversationOpened': return await conversationRegistry\.touch/)
  assert.match(sidebar, /formatTime\(item\.lastOpenedAt/)
})

test('卡片模式从空白工作台直接进入 Agent 对话', () => {
	const flow = between(clientSource, 'async function newCardConversation', 'function formatTime')
	const lifecycle = between(clientSource, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const recovery = between(clientSource, 'async function finishPendingOpen', 'async function retryPendingOpen')

	assert.doesNotMatch(flow, /window\.prompt/)
	assert.match(lifecycle, /call\("getResourceWorkspace"\)/)
	assert.match(serverSource, /case 'getResourceWorkspace': return \{ path: dataRoot \+ '\/resources' \}/)
	assert.match(lifecycle, /props\.workspaces\.create\(\{ path: resourceRoot\.path \}\)/)
	assert.match(lifecycle, /connectWorkspace: function/)
	assert.match(lifecycle, /call\("startChat"/)
	assert.match(lifecycle, /rememberPending: setPendingOpen/)
	assert.match(lifecycle, /finishOpen: finishPendingOpen/)
	assert.match(flow, /conversationLifecycle\.start/)
	assert.match(flow, /kind: "card", targetMode: "card"/)
	assert.match(recovery, /publishSessionMode\(pending\.sessionId, pending\.targetMode\)/)
  assert.match(recovery, /props\.openCardLibraryTab\(pending\.sessionId\)/)
  assert.match(recovery, /props\.openResourcesTab\(pending\.sessionId\)/)
  assert.ok(recovery.indexOf('props.openCardLibraryTab(pending.sessionId)') < recovery.indexOf('props.openResourcesTab(pending.sessionId)'))
})

test('游玩回复可只读交给同人物卡的卡片 Agent 调试', () => {
	const renderer = between(clientSource, 'function createTavernAssistantRendererFeatureModule', 'function createTavernShellFeatureModule')
	const status = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

	assert.doesNotMatch(renderer, /交给卡片 Agent 调试|dsh-tavern-assistant-debug/)
	assert.match(status, /正则加载不对？前端美化不对？内容生成不对？/)
	assert.match(status, /openPlayChatDebugWorkspace\(props\.sessionId, latestDebugTurn\)/)
	assert.match(status, /交给卡片 Agent 调试/)
	assert.doesNotMatch(status, /selectedDebugTurn|setDebugTurn|第 " \+ item\.turn \+ " 轮/)
	assert.match(clientSource, /dsh-tavern-debug-play-chat/)
	assert.match(sidebar, /getPlayChatDebugTarget/)
	assert.match(sidebar, /attachPlayChatDebug/)
	assert.match(sidebar, /"debug-play", "调试游玩对话"/)
	assert.match(serverSource, /name: 'tavern_read_play_chat'/)
	assert.match(serverSource, /case 'attachPlayChatDebug'/)
	assert.match(serverSource, /createPlayChatDebugReference/)
})

test('新建对话按会话类型选择 preset 以恢复被复用的冷 Session Agent', () => {
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const guard = between(sidebar, 'async function ensureTavernPreset', 'async function archiveCurrentBlankSession')
	const lifecycle = between(sidebar, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const playFlow = between(sidebar, 'async function newConversation', 'async function importCard')
	const cardFlow = between(sidebar, 'async function newCardConversation', 'function formatTime')

	assert.match(guard, /props\.conversationHost\.ensurePreset\(sessionId, request\)/)
	const adapter = between(clientSource, 'function createConversationHostAdapter', 'function createConversationLifecycleModule')
	assert.match(adapter, /agentPresets\.select\(sessionId, agentPreset\)/)
	assert.match(adapter, /ctx\.remote && ctx\.remote\.agentPresets/)
	assert.doesNotMatch(adapter, /"cordis"/)
	assert.match(adapter, /const agentPreset = "tavern"/)
	assert.doesNotMatch(guard, /agentPreset === "tavern"\) return/)
	assert.match(lifecycle, /ensurePreset: ensureTavernPreset/)
	assert.match(playFlow, /conversationLifecycle\.start/)
	assert.match(cardFlow, /conversationLifecycle\.start/)
  assert.doesNotMatch(playFlow, /agentPresets\.select/)
  assert.doesNotMatch(cardFlow, /agentPresets\.select/)
})

test('新建游玩和卡片对话等待前端 Session 列表就绪后再继续', () => {
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const waitFlow = between(sidebar, 'async function waitForSessionSummary', 'function isUnknownSessionSelectError')
	const recovery = between(clientSource, 'function createSessionListRecoveryModule', 'function createConversationHostAdapter')
	const lifecycle = between(sidebar, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const playFlow = between(sidebar, 'async function newConversation', 'async function importCard')
	const cardFlow = between(sidebar, 'async function newCardConversation', 'function formatTime')

	assert.match(waitFlow, /sessionListRecoveryRef\.current\.wait\(sessionId\)/)
	assert.match(recovery, /DSH Session 列表同步超时/)
	assert.match(lifecycle, /waitForSession: waitForSessionSummary/)
	assert.match(playFlow, /conversationLifecycle\.start/)
	assert.match(cardFlow, /conversationLifecycle\.start/)
})

test('已创建 Session 在前端列表短暂不同步时刷新并重连同一个 Session', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const openFlow = between(sidebar, 'async function openSessionWhenReady', 'async function finishPendingOpen')
  const recovery = between(clientSource, 'function createSessionListRecoveryModule', 'function createConversationHostAdapter')

  assert.match(recovery, /options\.summary\(sessionId\) && options\.binding\(sessionId\)/)
  assert.match(recovery, /await options\.refresh\(\)/)
  assert.match(recovery, /active\.has\(sessionId\)/)
  assert.match(recovery, /if \(!isUnknownSession\(error\)\) throw error/)
  assert.match(openFlow, /sessionListRecoveryRef\.current\.open\(sessionId\)/)
  assert.match(openFlow, /setError\(""\)/)
  const moduleOpen = between(recovery, 'async function open(sessionId)', 'return Object.freeze')
  const normalPath = moduleOpen.slice(0, moduleOpen.indexOf('catch (error)'))
  assert.doesNotMatch(normalPath, /refresh|wait/)
  assert.doesNotMatch(recovery, /connectWorkspace|startChat/)
})

test('游玩中可修改玩家称呼，Tavern 不接管正文发送状态', () => {
  const player = between(clientSource, 'function TavernPlayerNameAction', 'function TavernStatusPanel')

  assert.match(serverSource, /async function setPlayerName\(sessionId, userName\)/)
  assert.match(serverSource, /playerName: str\(chat\.macroState && chat\.macroState\.userName\)\.trim\(\) \|\| '你'/)
  assert.match(serverSource, /case 'setPlayerName'/)
  assert.match(player, /rpc\("setPlayerName", \{ userName: next \}, props\.sessionId\)/)
  assert.match(player, /仅影响之后生成的内容/)
  assert.match(clientSource, /id: "dsh-tavern-player-name"/)
  assert.doesNotMatch(clientSource, /TavernSignalTimeoutNotice/)
  assert.doesNotMatch(clientSource, /dsh-tavern-signal-timeout/)
})

test('Tavern 游玩对话顶栏显示创建时固化的整份预设', () => {
  const player = between(clientSource, 'function TavernPlayerNameAction', 'function TavernStatusPanel')
  const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')

  assert.match(view, /groupOfMode\(chat\.mode\) === 'play' && chat\.runtimePresetSnapshot/)
  assert.match(view, /runtimePreset: activePresetSnapshot === null \? null : \{ id: activePresetSnapshot\.presetPath, name: activePresetSnapshot\.presetName \}/)
  assert.match(player, /const presetName = view\.runtimePreset && view\.runtimePreset\.name \? view\.runtimePreset\.name : "无"/)
  assert.match(player, /"当前预设：" \+ presetName/)
  assert.match(clientSource, /dsh-tavern-preset-status/)
})

test('手机宽度隐藏顶栏长预设条目标签，避免挤压会话标题', () => {
	assert.match(clientCss, /@media \(max-width: 640px\)[\s\S]*\.dsh-tavern-preset-status \{ display: none; \}/)
})

test('后台协调快照不参与 Session 恢复、页面重载或正文锁定', () => {
  assert.doesNotMatch(serverSource, /case 'getSessionConnection'/)
  assert.match(serverSource, /case 'syncSession'/)
  assert.match(serverSource, /runtimeGeneration/)
  assert.match(serverSource, /agentRegistry\.get\(str\(args && args\.sessionId\)\)/)
  assert.doesNotMatch(clientSource, /createComposerGate/)
  assert.doesNotMatch(clientSource, /createRuntimeVersionGuard/)
  assert.doesNotMatch(clientSource, /createRuntimeConnectionCoordinator/)
  assert.doesNotMatch(clientSource, /conversation\.blocks/)
  assert.doesNotMatch(clientSource, /dsh-tavern:runtime-generation:v1/)
  assert.doesNotMatch(clientSource, /dsh-tavern:reconnect-draft:v1/)
})

test('新开游玩在创建 Session 前完成游戏准备，创建后不提供开场白切换器', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const prepareFlow = between(sidebar, 'async function preparePlayConversation', 'async function importCard')
  const openingChoice = between(sidebar, 'const openingChoice =', 'const playPicker =')

  assert.match(sidebar, /getCardOpenings/)
  assert.match(sidebar, /上一条开场白/)
  assert.match(sidebar, /下一条开场白/)
  assert.match(sidebar, /开始新游戏/)
  assert.match(sidebar, /游戏准备/)
	  assert.match(sidebar, /故事中的玩家称呼（可选）/)
	  assert.match(sidebar, /selectedOpening && selectedOpening\.usesUser/)
	  assert.match(sidebar, /不填则使用“你”/)
	  assert.match(serverSource, /projectCardOpeningPreviews\(/)
  assert.match(sidebar, /dsh-tavern-player-name/)
  assert.match(sidebar, /preparePlayConversation\(card\)/)
  assert.doesNotMatch(prepareFlow, /connectWorkspace|startChat/)
  assert.match(sidebar, /newConversation\(openingPicker\.card, null, selectedOpening \? selectedOpening\.id : "", openingPicker\.userName \|\| "你"\)/)
  assert.match(sidebar, /openingId: openingId \|\| ""/)
  assert.match(sidebar, /userName: resolvedUserName/)
  assert.match(sidebar, /dsh-tavern-picker-overlay/)
  assert.match(sidebar, /role: "dialog"/)
	assert.match(sidebar, /renderTavernProjection\(selectedOpening\.projection/)
	assert.match(openingChoice, /!busy && selectedOpening \? h\("div"/,
		'只有一个开场白时也必须在点击开始游戏前持续显示预览')
	assert.doesNotMatch(openingChoice, /!busy && selectedOpening && openingPicker\.openings\.length > 1/)
	assert.match(sidebar, /key: selectedOpening\.id/)
	assert.match(sidebar, /helperContext: selectedOpening\.helperContext/)
	assert.doesNotMatch(sidebar, /styleEnvironment/)
	assert.doesNotMatch(sidebar, /srcDoc: buildOpeningPreviewDocument\(selectedOpening\.text\)/)
	assert.match(clientCss, /\.dsh-tavern-greeting-preview \{[^\n]*background: var\(--dsw-specific-sidebar-fill\)/)
	assert.match(clientCss, /\.dsh-tavern-greeting-preview \{[^\n]*overflow-anchor: none/)
	assert.doesNotMatch(clientCss, /\.dsh-tavern-greeting-preview \{[^\n]*background: #fff/)
	assert.doesNotMatch(sidebar, /展示页不可作为开场/)
})

test('开场白创建失败时在选择弹窗内持续显示具体阶段和错误', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const refresh = between(sidebar, 'function refresh()', 'React.useEffect(function ()')
  const playFlow = between(sidebar, 'async function newConversation', 'async function preparePlayConversation')
  const lifecycle = between(clientSource, 'function createConversationLifecycleModule', 'function isIgnoredTavernError')

  assert.match(sidebar, /const pickerError = error \? h\("div", \{ className: "dsh-tavern-picker-error", role: "alert" \}/)
  assert.match(sidebar, /重新连接已创建的 Session/)
  assert.match(sidebar, /const playPicker = h\("div",[^\n]+pickerError/)
  assert.match(sidebar, /!picking && error \? h\("div", \{ className: "dsh-tavern-dock-error", role: "alert" \}/)
  assert.doesNotMatch(refresh, /setError\(""\)/)
  assert.match(lifecycle, /let phase = "清理当前空白对话"/)
  assert.match(lifecycle, /phase = "创建 DSH Session"/)
  assert.match(lifecycle, /phase = request\.kind === "card" \? "创建卡片工作台对话" : "写入人物卡开场白"/)
  assert.match(lifecycle, /failure\.phase = phase/)
  assert.match(playFlow, /err && err\.phase/)
})

test('Tavern 错误面板只保留最新错误，左侧栏连接恢复后撤销轮询错误', () => {
  const errorHub = between(clientSource, 'const tavernErrorHub', 'function usePersistentError')
  const errorCenter = between(clientSource, 'function TavernErrorCenter', 'const tavernSessionModes')
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(errorHub, /\.slice\(0, 1\)/)
  assert.match(errorHub, /const existing = items\[0\]/)
  assert.match(errorHub, /count: existing\.count \+ 1/)
  assert.doesNotMatch(errorHub, /slice\(0, 20\)/)
  assert.match(errorHub, /dismiss: function \(id\)/)
  assert.match(errorHub, /resolve: function \(source, beforeAt\)/)
  assert.match(errorHub, /Number\(items\[0\]\.lastAt\) >= cutoff/)
  assert.match(errorHub, /clear: function \(\)/)
  assert.doesNotMatch(errorHub, /setTimeout|setInterval/)
  assert.match(errorHub, /window\.sessionStorage\.getItem\(storageKey\)/)
  assert.match(errorHub, /window\.sessionStorage\.setItem\(storageKey, JSON\.stringify\(items\)\)/)
  assert.match(errorCenter, /最新错误/)
  assert.doesNotMatch(errorCenter, /复制全部|全部清除/)
  assert.match(errorCenter, /"复制"/)
  assert.match(errorCenter, /"清除"/)
  assert.match(clientSource, /const lastReported = React\.useRef\(""\)/)
  assert.match(clientSource, /visible !== lastReported\.current/)
  assert.match(clientSource, /if \(!visible\) tavernErrorHub\.resolve\(source\)/)
  assert.match(sidebar, /if \(collapsed\) return h\(React\.Fragment, null,\s*h\(TavernErrorCenter\)/)
  assert.match(sidebar, /return h\(React\.Fragment, null, h\(TavernErrorCenter\)/)
  assert.match(clientSource, /usePersistentError\("左侧栏操作"\)/)
  assert.match(sidebar, /latest\.message === "DSH Session 列表同步超时，请刷新页面后重试：" \+ current/)
  assert.match(sidebar, /latest\.source !== "左侧栏操作"/)
  assert.match(sidebar, /tavernErrorHub\.resolve\("左侧栏人物卡"\)/)
  assert.match(sidebar, /tavernErrorHub\.resolve\("左侧栏历史"\)/)
  assert.match(sidebar, /tavernErrorHub\.report\("左侧栏人物卡", err\)/)
  assert.match(sidebar, /tavernErrorHub\.report\("左侧栏历史", err\)/)
  assert.match(clientSource, /usePersistentError\("剧本库"\)/)
  assert.match(clientSource, /usePersistentError\("预设库"\)/)
  assert.doesNotMatch(clientSource, /usePersistentError\("破限方案库"\)/)
  assert.match(clientSource, /usePersistentError\("人物卡库"\)/)
  assert.match(clientSource, /usePersistentError\("人物卡详情"\)/)
  assert.match(clientSource, /usePersistentError\("剧本管理"\)/)
  assert.match(clientSource, /usePersistentError\("Guide"\)/)
  assert.match(clientSource, /usePersistentError\("酒馆状态"\)/)
  assert.match(clientSource, /tavernErrorHub\.report\("候选项生成", err\)/)
  assert.match(clientSource, /tavernErrorHub\.report\("正文重新生成", err\)/)
  assert.match(clientSource, /tavernErrorHub\.report\("插件更新", err\)/)
  assert.match(clientSource, /function isIgnoredTavernError\(value\)/)
  assert.match(errorHub, /if \(isIgnoredTavernError\(error\) && !error\?\.dshTavernModuleFailure\) return/)
  assert.match(clientSource, /const visible = isIgnoredTavernError\(message\) \? "" : message/)
  assert.match(clientSource, /setLocalError\(visible\)/)
})

test('展示投影通过正式消息 renderer 渲染，并在配置变化后重算历史', () => {
  const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')
  const renderer = between(clientSource, 'function createTavernAssistantRendererFeatureModule', 'function createTavernShellFeatureModule')

  assert.match(serverSource, /function replyProjectionsOf\(chat\)/)
  assert.match(view, /projectRuntimeReplyHistory\(chat\.messages/)
  assert.match(view, /replyProjections: replyDisplay\.projections/)
  assert.match(view, /inputSources/)
  assert.match(renderer, /key: "assistant-step"/)
  assert.match(renderer, /key: "user"/)
  assert.match(renderer, /priority: -1/)
  assert.match(renderer, /useLiveTavernView\(props\.sessionId/)
  assert.match(renderer, /tavernStoryTurnForDshTurn\(liveState\.view, turn\)/)
  assert.match(renderer, /tavernProjectionForTurn\(liveState\.view, storyTurn\)/)
  assert.match(renderer, /tavernUserTextForTurn\(liveState\.view, turn, data\.content\)/)
  assert.doesNotMatch(clientSource, /function applyReplyProjections|dsh-tavern-projected-reply/)
})

test('候选项列表限制高度并独立滚动，底部操作保持在滚动区外', () => {
  const question = between(clientSource, 'function CandidateQuestion', 'function CandidateGuidePanel')

  assert.match(clientCss, /\.dsh-tavern-question-body \{ max-height: min\(360px, 45vh\); overflow-y: auto;/)
  assert.match(question, /className: "dsh-tavern-question-body"/)
  assert.ok(question.indexOf('className: "dsh-tavern-question-body"') < question.indexOf('className: "dsh-tavern-question-foot"'))
})

test('自由行动只聚焦输入框并保留已生成候选项', () => {
  const question = between(clientSource, 'function CandidateQuestion', 'function CandidateGuidePanel')
  const label = '"✎ 自由行动（直接在下方输入）"'
  const labelIndex = question.indexOf(label)
  const handlerStart = question.lastIndexOf('onClick:', labelIndex)
  const handler = question.slice(handlerStart, labelIndex)

  assert.notEqual(labelIndex, -1)
  assert.match(handler, /document\.querySelector\("\[data-composer-card\] textarea"\)/)
  assert.match(handler, /input\.focus\(\)/)
  assert.doesNotMatch(handler, /setCandidatePanel\(null\)/)
})

test('后台结算期间禁用候选项按钮，完成后自动恢复', () => {
  const action = between(clientSource, 'function CandidateAction', 'function CandidateDockActions')
  const coordination = between(clientSource, 'const tavernCoordination', 'function describeTavernActivity')
  const submit = between(clientSource, 'async function submitCandidateTask', 'const regenPanel')
  const guide = between(clientSource, 'function CandidateGuidePanel', 'function RegenPanel')
  const activity = between(serverSource, 'async function sessionActivity', 'async function sessionView')

  assert.match(serverSource, /case 'syncSession'/)
  assert.match(serverSource, /case 'submitTask'/)
  assert.match(activity, /const activity = backgroundTasks\.activity\(chat\)/)
  assert.doesNotMatch(activity, /settleStatus/)
  assert.doesNotMatch(activity, /view\(|readChatCard|projectRuntimeReplyHistory/)
  assert.doesNotMatch(clientSource, /dsh-tavern-activity-gate/)
  assert.match(action, /useTavernCoordination\(props\.sessionId/)
  assert.match(action, /disabled:.*activity\.busy/s)
	assert.match(action, /settlementActive = activity\.role === "settlement"/)
	assert.match(action, /disabled: frontRunning \|\| \(activity\.busy && !settlementActive\) \|\| regenBusy/)
  // Rollback busy/retry behavior is exercised by the real component in rollback-action.test.mjs.
  assert.match(clientSource, /"后台结算中…"/)
  assert.match(action, /props\.refreshSessions\(\)/)
  assert.match(action, /submitCandidateTask\(props\.sessionId, props\.messageId, guidance\)/)
  assert.match(guide, /submitCandidateTask\(props\.sessionId, messageId, guide\)/)
  assert.doesNotMatch(clientSource, /rpc\("generateChoices"/)
  assert.match(submit, /rpc\("submitTask"/)
  assert.match(submit, /tavernCoordination\.setView\(sessionId/)
  assert.match(remoteClientSource, /new RemoteSnapshotStream/)
  assert.match(coordination, /tavernSessionSignals\.subscribe/)
  assert.match(coordination, /rpc\("syncSession"/)
  assert.doesNotMatch(coordination, /setTimeout|setInterval/)
  assert.doesNotMatch(serverSource, /case 'generateChoices'/)
  assert.doesNotMatch(action, /rpc\("getSession"/)
})

test('酒馆状态读取 MVU 回执时使用当前模块可用的复制能力', () => {
	const receipts = between(serverSource, 'function mvuReceiptsOf', 'function withLegacyPresentationProjection')

	assert.match(receipts, /structuredClone\(stored\)/)
	assert.doesNotMatch(receipts, /\bclone\(stored\)/)
})

test('失败的最新后台结算可以按原任务类型原地重试', () => {
	const retry = between(serverSource, 'async function retrySettlement', 'async function pullBackgroundCycle')
	const settlement = between(serverSource, 'async function runSettlement', 'function queueSettlement')
	const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')
	assert.match(retry, /只能重试当前最新正文的后台结算/)
	assert.match(retry, /target\.message\.mvu = \{ pending: true/)
	assert.match(retry, /void queueSettlement\(chat\.id\)/)
	assert.match(serverSource, /case 'retrySettlement': return \{ view: await retrySettlement/)
	assert.match(retry, /source: 'settlement\.retry'/)
	assert.match(settlement, /latest\.settleStatus = 'failed'/)
	assert.match(settlement, /source: target === null \? 'settlement\.posture-failed' : 'settlement\.mvu-failed'/)
	assert.match(view, /settleError: activity\.reason === 'interrupted'/)
	assert.match(view, /settlementTurn: settlementTurn\(chat\)/)
})

test('正文重新生成合并为一个入口，空意见和有意见复用同一替换流程', () => {
	const action = between(clientSource, 'function CandidateAction', 'function CandidateDockActions')
	const shared = between(clientSource, 'async function submitBodyRegeneration', 'function CandidateAction')
	const panel = between(clientSource, 'function RegenPanel', 'function register')

	assert.match(action, /"重新生成正文"/)
	assert.doesNotMatch(action, /"一键重新生成正文"|"带意见重新生成正文"/)
	assert.match(action, /onClick: openRegeneration/)
	assert.match(panel, /submitBodyRegeneration\(props\.sessionId, panel, guide\)/)
	assert.match(shared, /rpc\("regenBody", \{ guidance:/)
	assert.match(shared, /applyBodyRegenerationResult\(\{ liveTavernView:/)

})

test('回合操作接入独立流程，历史投影不再由候选面板维护', () => {
  assert.match(serverSource, /createRoundHistory\(\{/)
  assert.match(serverSource, /case 'regenBody': return \{ view: await regenBody/)
  assert.match(serverSource, /case 'rollbackTurn': return \{ view: await rollbackTurn/)
  const candidate = between(clientSource, 'function CandidateQuestion', 'function CandidateGuidePanel')
  assert.doesNotMatch(candidate, /MutationObserver|applySuppressedDshTurns|suppressionState/)
  const history = between(clientSource, 'function TurnHistoryProjection', 'function CandidateQuestion')
  assert.match(history, /historyProjection\.apply\(props.sessionId, suppressedDshTurns, regeneratedDshTurns\)/)
  assert.match(clientSource, /createElement\(TurnHistoryProjection,/)
})

test('人物卡详情支持查看、追加、排序和逐本解绑世界书', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernPlayerNameAction')
  const dispatch = between(serverSource, 'async function dispatch', 'const webServer')

  assert.match(dispatch, /case 'getWorldBookBinding'/)
  assert.match(dispatch, /case 'bindWorldBook'/)
  assert.match(dispatch, /case 'unbindWorldBook'/)
  assert.match(panel, /call\("getWorldBookBinding", \{ cardPath: cardPath \}\)/)
	assert.match(panel, /rpcWithTimeout\("listWorldBooks", \{\}\)/)
  assert.match(panel, /ownWorldBookName \+ "（当前人物卡）"/)
  assert.match(panel, /call\("bindWorldBook", \{ cardPath: cardPath, source: source \}\)/)
  assert.match(panel, /call\("unbindWorldBook", \{ cardPath: cardPath, source: source \}\)/)
  assert.match(panel, /call\("setWorldBookBindings"/)
  assert.doesNotMatch(panel, /hasWorldBookBinding \? null : h\("select"/)
  assert.match(panel, /多本世界书可能相互冲突，引发异常/)
  assert.match(panel, /props\.onOpenWorldBook\(book\.source\)/)
  assert.match(panel, /dsh-tavern-worldbook-bound/)
})

test('人物卡绑定下拉框同时列出独立与其他人物卡的内置世界书', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernPlayerNameAction')

  assert.match(panel, /\(result\.standalone \|\| \[\]\)\.concat\(result\.embedded \|\| \[\]\)/)
  assert.match(panel, /return item\.kind === "card" \? "card:" \+ item\.cardPath : "standalone:" \+ item\.path/)
  assert.match(panel, /return \{ kind: "card", cardPath: value\.slice\(5\) \}/)
  assert.match(panel, /return \{ kind: "standalone", path: value\.slice\(11\) \}/)
  assert.match(panel, /item\.kind === "card" && item\.cardPath === cardPath/)
  assert.match(panel, /item\.name \+ "（人物卡：" \+ item\.cardName/)
})

test('新建对话把缺失的当前空 Session 视为已归档', () => {
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const archiveBlank = between(sidebar, 'async function archiveCurrentBlankSession', 'async function waitForSessionSummary')
	const lifecycle = between(sidebar, 'const conversationLifecycle = createConversationLifecycleModule', 'async function retryPendingOpen')
	const playFlow = between(sidebar, 'async function newConversation', 'async function preparePlayConversation')
	const cardFlow = between(sidebar, 'async function newCardConversation', 'function formatTime')

  assert.match(archiveBlank, /props\.workspaces\.archiveSession\(current\)/)
  assert.match(archiveBlank, /if \(!isMissingSessionArchiveError\(archiveError\)\) throw archiveError/)
	assert.match(lifecycle, /archiveCurrent: archiveCurrentBlankSession/)
	assert.match(playFlow, /conversationLifecycle\.start/)
	assert.match(cardFlow, /conversationLifecycle\.start/)
})

test('创建对话失败时服务端记录请求边界但不记录开场白正文', () => {
  const dispatch = between(serverSource, 'async function dispatch', 'const webServer')

  assert.match(dispatch, /console\.error\('dsh-tavern: 创建对话失败'/)
  assert.match(dispatch, /cardPath: str\(args && args\.path\)/)
  assert.match(dispatch, /openingId: str\(args && args\.openingId\)/)
  assert.doesNotMatch(dispatch, /greeting|openingText/)
})

test('卡片模式通过人物卡、剧本、世界书、预设和空白入口进入同一个 Agent', () => {
  const flow = between(clientSource, 'async function newCardConversation', 'function formatTime')
  const recovery = between(clientSource, 'async function finishPendingOpen', 'async function retryPendingOpen')

  assert.match(clientSource, /"修改人物卡"/)
  assert.match(clientSource, /"把人物卡转成 MVU 版"/)
  assert.match(clientSource, /"从剧本新建人物卡"/)
  assert.match(clientSource, /"修改剧本"/)
  assert.match(clientSource, /"修改世界书"/)
  assert.match(clientSource, /"修改预设"/)
  assert.match(clientSource, /作为编辑目标引用，不会在当前 Agent 中运行/)
  assert.match(clientSource, /dsh-tavern-edit-preset/)
  assert.match(clientSource, /newCardConversation\(null, "preset", "修改预设", \[\{ kind: "preset"/)
  assert.match(clientSource, /"空白开始"/)
	assert.doesNotMatch(clientSource, /请先从右侧侧边栏的对应资源库导入人物卡、剧本、世界书或预设文件。/)
	assert.match(clientSource, /initialImportLabel = cardEntry === "worldbook" \? "导入世界书"/)
	assert.match(clientSource, /cardEntry === "extract" \|\| cardEntry === "script" \? "导入剧本"/)
	assert.match(clientSource, /importInitialResource\(f, cardEntry\)/)
	assert.match(clientSource, /暂无可选.*可点击右上角导入/)
	assert.match(flow, /kind: "card", targetMode: "card"/)
  assert.match(flow, /task: task, label: label, card: card, selectedResources: selectedResources \|\| \[\]/)
  assert.match(recovery, /if \(pending\.task\) await props\.injectTaskPrompt\(pending\.sessionId, pending\.task, pending\.label, pending\.card, \(pending\.selectedResources \|\| \[\]\)\.length > 0, pending\.taskSupplement\)/)
  assert.doesNotMatch(clientSource, /\bstartExtract\b|newExtractSession|"revision"|mode: "extract"/)
  assert.doesNotMatch(clientSource, /attachSourcesToCurrent|attachCardToCurrent/)
  assert.match(clientSource, /return values\[sessionId\] \|\| "";/)
})

test('人物卡转 MVU 起始任务写入 Skill、目标卡与简短转换要求', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const injectTaskPrompt = between(clientSource, 'async function injectTaskPrompt', 'playControlsFeature.register')

  assert.match(sidebar, /cardEntry === "mvu"/)
  assert.match(sidebar, /newCardConversation\(card, "mvu", "把人物卡转成 MVU 版"\)/)
  assert.match(sidebar, /转换为 MVU 后，状态栏绝对不会掉格式/)
  assert.match(injectTaskPrompt, /if \(task === "mvu"\)/)
  assert.match(injectTaskPrompt, /\/tavern-card-to-mvu\\n\\n【目标人物卡】\\n@/)
  assert.match(injectTaskPrompt, /把这张人物卡转换为独立的 MVU 版本/)
  assert.match(injectTaskPrompt, /移除原卡自带的候选项生成提示、按钮、正则和专用脚本/)
  assert.match(injectTaskPrompt, /统一使用 DSH Tavern 内置候选项/)
})

test('用户画像只从右侧栏进入，开场准备和起始任务不展示画像', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const injectTaskPrompt = between(clientSource, 'async function injectTaskPrompt', 'playControlsFeature.register')

  assert.match(sidebar, /newCardConversation\(null, "user-profile", "建立用户画像"\)/)
  const opening = between(sidebar, 'const openingChoice', 'const playPicker')
  const taskPicker = between(sidebar, 'const cardPicker', 'const updateMessage')
  assert.doesNotMatch(opening, /用户画像|userProfile|长期偏好/)
  assert.doesNotMatch(taskPicker, /用户画像|user-profile/)
  assert.match(injectTaskPrompt, /if \(task === "user-profile"\)/)
  assert.match(injectTaskPrompt, /\/tavern-user-profile/)
  assert.doesNotMatch(sidebar, /userProfileEnabled|response\.userProfile/)
})

test('用户画像右侧栏聚焦实际生效偏好，详细依据折叠并可跳转卡片 Agent', () => {
  const profileTab = between(clientSource, 'function UserPreferenceProfileTab', 'function SystemPromptSidebarTab')
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(profileTab, /getUserPreferenceProfile/)
  assert.match(profileTab, /updateUserPreferenceProfile/)
  assert.match(profileTab, /setUserPreferenceProfileDefaultEnabled/)
  assert.doesNotMatch(profileTab, /完整画像/)
  assert.match(profileTab, /实际生效的偏好/)
  assert.match(profileTab, /偏好维度/)
  assert.match(profileTab, /原始回答/)
  assert.match(profileTab, /新游戏默认启用/)
  assert.match(profileTab, /仅在此处开启或关闭/)
  assert.doesNotMatch(profileTab, /准备页仍可单局覆盖/)
  assert.match(profileTab, /本局创建后保持冻结/)
  assert.match(profileTab, /dsh-tavern-open-user-profile-task/)
  assert.match(sidebar, /addEventListener\("dsh-tavern-open-user-profile-task"/)
  assert.match(serverSource, /case 'getUserPreferenceProfile'/)
  assert.match(serverSource, /case 'updateUserPreferenceProfile'/)
  assert.match(serverSource, /case 'setUserPreferenceProfileDefaultEnabled'/)
  assert.match(clientSource, /id: "dsh-tavern:user-profile"/)
})

test('世界书与预设起始任务先选择一个目标并自动追加类型引用', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(sidebar, /call\("listWorldBooks"\)/)
  assert.match(sidebar, /call\("listPresets"\)/)
  assert.match(sidebar, /newCardConversation\(null, "worldbook", "修改世界书"/)
  assert.match(sidebar, /newCardConversation\(null, "preset", "修改预设"/)
  assert.match(sidebar, /kind: "worldbook"/)
  assert.match(sidebar, /kind: "preset"/)
})

test('世界书库在卡片对话中可引用独立或内置世界书', () => {
  const panel = between(clientSource, 'function createWorldBookLibraryFeatureModule', 'const worldBookLibraryFeature')

  assert.match(panel, /props\.appendMention\("worldbook"/)
  assert.match(panel, /在对话中引用/)
  assert.match(panel, /sessionMode === "card"/)
  assert.match(clientSource, /tavern-worldbook:/)
})

test('人物卡抽取与剧本修改都使用剧本库，并自动追加引用', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const recovery = between(sidebar, 'async function finishPendingOpen', 'async function retryPendingOpen')

  assert.match(sidebar, /async function openResourcePicker\(task\)/)
  assert.match(sidebar, /const response = await call\("listResources"\)/)
  assert.match(sidebar, /kind: "source"/)
  assert.match(sidebar, /initialResourceGroup\(initialResourceTitle, initialResources\)/)
  assert.doesNotMatch(sidebar, /initialResourceGroup\("素材"/)
  assert.doesNotMatch(sidebar, /initialResourceGroup\("已绑定剧本"/)
  assert.match(sidebar, /disabled: busy \|\| !chosenInitialResources\.length/)
  assert.match(sidebar, /newCardConversation\(null, "extract", "从剧本新建人物卡", chosenInitialResources\)/)
  assert.match(sidebar, /newCardConversation\(null, "script", "修改剧本", chosenInitialResources\)/)
  assert.match(recovery, /\(pending\.selectedResources \|\| \[\]\)\.forEach/)
  assert.match(recovery, /props\.appendMention\(pending\.sessionId, resource\.kind, resource\.path, resource\.title\)/)
  assert.doesNotMatch(recovery, /pending\.task === "boundary"/)
  assert.match(sidebar, /先选择一份剧本，再进入工作台修改工作版/)
  assert.doesNotMatch(sidebar, /newCardConversation\(null, "extract", "从素材新建人物卡"\);/)
})

test('卡片任务只在创建对话时追加提示词，不占用输入框上方区域', () => {
  assert.match(clientSource, /rpc\("getCardTaskPrompt", \{ task: task \}, sessionId\)/)
  assert.match(clientSource, /【目标人物卡】/)
  assert.match(clientSource, /card && card\.path/)
  assert.match(clientSource, /@\\"/)
  assert.match(clientSource, /input\.setDraft\(taskText \+ supplement\)/)
  assert.match(clientSource, /task === "worldbook" \|\| task === "preset"/)
  assert.match(clientSource, /【初始剧本】/)
  assert.match(clientSource, /【编辑目标】/)
  assert.doesNotMatch(clientSource, /【补充要求】/)
  assert.doesNotMatch(clientSource, /function CardTaskDockActions/)
  assert.doesNotMatch(clientSource, /id: "dsh-tavern-card-tasks"/)
  assert.doesNotMatch(clientSource, /choose\("bindScript"/)
})

test('空白工作台确认后自动创建人物卡，不再提供二次保存按钮', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const sessionList = between(serverSource, 'async function listTavernSessions()', 'async function addGuide')
  const coordination = between(clientSource, 'const tavernCoordination = createTavernCoordinationEventModule', 'function describeTavernActivity')

  assert.doesNotMatch(clientSource, /CardDraftPanel|finalizeCard|保存为新人物卡|写入草稿/)
  assert.doesNotMatch(serverSource, /case 'finalizeCard'/)
  assert.match(sidebar, /const currentSummary = current \? summaries\[current\] : null;/)
  assert.match(sidebar, /if \(!currentSummary \|\| currentSummary\.blank\) return;\s*notifyDataChanged\(\["sessions"\]\);/)
  assert.match(sessionList, /return await conversationRegistry\.list\(\)/)
  // Candidate task projection is exercised through its production interface.
  assert.match(clientSource, /cardPath: String\(sync\.cardPath \|\| ""\)/)
  assert.match(coordination, /previous === "" && cardPath !== ""/)
  assert.match(coordination, /notifyTavernDataChanged\(\["cards", "sessions"\], "coordination"\)/)
  assert.match(sidebar, /tavernCoordination\.subscribe\(current, function \(\) \{\}\)/)
  assert.match(sidebar, /尚未创建正式人物卡/)
  assert.match(sidebar, /已创建：/)
})

test('Tavern 只接管会话区域，保留 DSH 原生设置与模型配置入口', () => {
  assert.match(clientSource, /slots\.inject\("sidebar\.workspaces"/)
  assert.doesNotMatch(clientSource, /slots\.inject\("sidebar",/)
})

test('游玩不提供 Swipe 分支切换，只保留整轮正文重新生成', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  assert.doesNotMatch(sidebar, /switchOpening\(|call\("switchOpening"/)
	const assistant = between(clientSource, 'function TavernAssistantNodeView', 'function register')
	assert.doesNotMatch(assistant, /switchTavernSwipe/)
	assert.doesNotMatch(assistant, /上一个 Swipe/)
	assert.doesNotMatch(assistant, /下一个 Swipe/)
	assert.doesNotMatch(serverSource, /case 'switchTavernSwipe'/)
})

test('酒馆状态页注册到 Better Sidebar，不再接管 DSH details', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function CardFieldsPanel')

  assert.match(sidebar, /readyTavernSession/)
  assert.match(sidebar, /summaries\[current\]\.blank === false/)
  assert.match(sidebar, /history\.some\(function \(entry\) \{ return entry\.sessionId === current && isPlayMode\(entry\.mode\); \}\)/)
  assert.match(sidebar, /props\.openStatusTab\(readyTavernSession\)/)
  assert.match(sidebar, /props\.openStatusTab\(pending\.sessionId\)/)
  assert.match(clientSource, /ctx\.betterSidebar\.registerTab\(\{/)
  assert.match(clientSource, /id: "dsh-tavern:status"/)
  assert.match(clientSource, /patch: \{ panelOpen: true \}/)
  assert.doesNotMatch(clientSource, /className: "dsh-tavern-status-presentation"/)
  assert.doesNotMatch(clientSource, /buildOpeningPreviewDocument\(view\.presentation\.html\)/)
  assert.match(clientSource, /ctx\.betterSidebar\.openTab\(\{ type: "dsh-tavern:status" \}/)
  assert.doesNotMatch(clientSource, /slots\.inject\("details"|openDetails|ensureDetailsOpen/)
})

test('左侧栏常驻显示版本与构建号，并把检查更新和进行更新分成两步', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(sidebar, /call\("getUpdateStatus"/)
  assert.match(sidebar, /call\("checkUpdate"/)
  assert.match(sidebar, /call\("startUpdate"/)
  assert.match(sidebar, /DSH Tavern /)
  assert.match(sidebar, /currentVersionLabel/)
  assert.match(sidebar, /currentCommitLabel/)
  assert.match(sidebar, /检查更新/)
  assert.doesNotMatch(sidebar, /重新检查/)
  assert.match(sidebar, /进行更新/)
  assert.match(sidebar, /updateStatus\.phase !== "update-available"/)
  assert.match(sidebar, /正在通过 jsDelivr 检查最新构建/)
  assert.match(sidebar, /未发现更新构建/)
  assert.match(sidebar, /发现新构建/)
  assert.match(sidebar, /未发现更新构建/)
  assert.match(sidebar, /tavern-update-probe/)
  assert.match(sidebar, /recovery\.sawOffline/)
  assert.match(sidebar, /window\.location\.reload\(\)/)
  assert.match(sidebar, /程序文件已更新，但自动重启失败/)
  assert.match(sidebar, /请手动重启/)
  assert.match(sidebar, /更新期间会短暂断开/)
  assert.match(sidebar, /如果较长时间仍未更新完成，建议重新安装一次/)
  assert.match(sidebar, /检测到 Git 时只会下载运行所需代码/)
  assert.match(sidebar, /请重启 DSH Desktop/)
  assert.match(sidebar, /更新完成，请刷新页面/)
  assert.match(sidebar, /Android 版/)
  assert.match(sidebar, /3088/)
  assert.match(sidebar, /未知方法:\s*getUpdateStatus/)
  assert.match(sidebar, /请重启 DSH Desktop 以加载新版插件/)
  assert.match(sidebar, /重启 Desktop 后可用/)
  assert.match(serverSource, /case 'getUpdateStatus'/)
  assert.match(serverSource, /case 'checkUpdate'/)
  assert.match(serverSource, /case 'startUpdate'/)
})

test('持久化的更新完成状态不是刷新命令，页面只在服务实际离线恢复后刷新一次', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(sidebar, /recovery\.sawOffline/)
  assert.equal((sidebar.match(/window\.location\.reload\(\)/g) || []).length, 1)
  assert.doesNotMatch(sidebar, /updateStatus\.phase !== "completed"[\s\S]{0,300}window\.location\.reload\(\)/)
  assert.match(sidebar, /updateStartedAtRef\.current > 0/)
  assert.match(sidebar, /status\.completedAt[\s\S]{0,120}updateStartedAtRef\.current/)
  assert.match(sidebar, /status\.phase === "completed" && !completedInThisPage \? \{ \.\.\.status, phase: "idle"/)
})

test('旧破甲侧栏、RPC 和卡片入口已删除', () => {
  assert.doesNotMatch(clientSource, /BoundaryPromptTab|listBoundaryPrompts|从预设提取破甲/)
  assert.equal((clientSource.match(/dsh-tavern:boundary-prompts/g) || []).length, 1)
  assert.doesNotMatch(serverSource, /createBoundaryPromptModule|listBoundaryPrompts|tavern_update_boundary_prompt/)
  assert.match(clientSource, /tab\.type === "dsh-tavern:boundary-prompts".*retiredTabs\.push/)
  assert.match(clientSource, /betterSidebar\.closeTab\(tabId/)
})

test('卡片编辑读取保留人物卡宏，只在游玩投影中展开', () => {
  const cardReader = between(serverSource, "name: 'tavern_read_card'", "name: 'tavern_read_card_raw'")
  const worldBookReader = between(serverSource, "name: 'tavern_read_worldbook'", "name: 'tavern_update_card'")

  assert.doesNotMatch(cardReader, /projectCardMacros|projectCardText/)
  assert.doesNotMatch(worldBookReader, /projectCardMacros|projectCardText/)
})

test('预设库选择整份预设，并可交给卡片 Agent 编辑或在当前对话引用', () => {
  const panel = between(clientSource, 'function createExternalPresetAndBypassPlanFeatureModule', 'function createWorldBookLibraryFeatureModule')

  assert.match(panel, /title: "预设库"/)
  assert.doesNotMatch(clientSource, /预设库（实验性）/)
  assert.doesNotMatch(panel, /title: "破限方案库（实验性）"/)
  assert.match(panel, /当前预设/)
  assert.match(panel, /dsh-tavern-external-preset-notice/)
  assert.match(panel, /rpc\("selectPreset"/)
  assert.match(panel, /dsh-tavern-preset-selector/)
  assert.match(panel, /当前使用的预设/)
  assert.match(panel, /不使用外部预设（默认）/)
  assert.match(panel, /onChange: function \(event\) \{ selectPreset\(event\.target\.value\); \}/)
  assert.match(panel, /一般用内置设置就够了/)
  assert.match(panel, /在卡片模式里让 Agent 修改人物卡/)
  assert.match(panel, /外部预设也会影响模型怎么写/)
  assert.match(panel, /当前使用内置设置/)
  assert.match(panel, /同一份预设不一定有同样的效果/)
  assert.doesNotMatch(panel, /按头部、中部和尾部加入 DSH 前台正文请求/)
  assert.doesNotMatch(panel, /"使用预设"/)
  assert.doesNotMatch(panel, /"使用中"/)
  assert.doesNotMatch(panel, /"停用预设"/)
  assert.doesNotMatch(panel, /破限效果|除非坚持|系统行为异常，请用户自行判断/)
  assert.doesNotMatch(panel, /兼容边界：/)
  assert.doesNotMatch(panel, /兼容模式|兼容（实验性）/)
  assert.match(panel, /"在对话中引用"/)
  assert.match(panel, /props\.appendMention\("preset"/)
  assert.match(panel, /"← 返回预设库"/)
	assert.match(panel, /编辑前／中／后三段预设/)
	assert.match(panel, /前、中、后表示这些内容放在提示词的什么位置/)
	assert.match(panel, /这里的修改只对新开的一局生效/)
	assert.match(panel, /已经开始的游戏仍用开局时的预设/)
	assert.match(panel, /酒馆的预设可以导入使用/)
	assert.match(panel, /想用修改后的预设，需要新开一局/)
	assert.doesNotMatch(panel, /下一轮游玩请求直接生效|保存后下一轮游玩直接生效/)
  assert.match(panel, /预设会影响游玩时的正文生成/)
  assert.match(panel, /负责后台工作的 Agent 不使用这些预设/)
  assert.match(panel, /"提示词三段 · "/)
  assert.match(panel, /"前段"/)
  assert.match(panel, /"中段"/)
  assert.match(panel, /"后段"/)
  assert.match(panel, /放在系统提示词的开头/)
  assert.match(panel, /放进每轮的任务说明里/)
  assert.match(panel, /在本轮输入和任务说明之后/)
  assert.match(panel, /"正则脚本 · "/)
  assert.match(panel, /dsh-tavern-prompt-row/)
  assert.match(panel, /savePresetEntry/)
  assert.match(panel, /savePresetRegex/)
  assert.match(panel, /"保存此条目"/)
  assert.match(panel, /"保存此正则"/)
  assert.match(panel, /patch: \{ name: draft\.name, role: draft\.role, content: draft\.content, enabled: draft\.enabled \}/)
  assert.match(panel, /patch: \{ name: draft\.name, findRegex: draft\.findRegex, replaceString: draft\.replaceString, enabled: draft\.enabled \}/)
  assert.match(panel, /rpc\("updatePresetEntry"/)
  assert.match(panel, /rpc\("updatePresetRegex"/)
  assert.match(panel, /async function togglePresetEntry\(entry\)/)
  assert.match(panel, /patch: \{ enabled: enabled \}/)
  assert.match(panel, /点击停用此条目/)
  assert.match(panel, /点击启用此条目/)
  assert.match(panel, /async function togglePresetRegex\(script\)/)
  assert.match(panel, /点击停用此正则/)
  assert.match(panel, /点击启用此正则/)
  assert.match(panel, /event\.preventDefault\(\); event\.stopPropagation\(\); togglePresetEntry\(entry\)/)
  assert.match(panel, /event\.preventDefault\(\); event\.stopPropagation\(\); togglePresetRegex\(script\)/)
  assert.match(panel, /系统占位状态只读/)
  assert.match(panel, /dsh-tavern-preset-detail-actions/)
  assert.match(panel, /className: "dsh-tavern-btn danger"[\s\S]*"删除"/)
  assert.ok(panel.indexOf('dsh-tavern-preset-detail-actions') < panel.indexOf('"提示词三段 · "'))
  assert.doesNotMatch(panel, /"编辑预设"|dsh-tavern-edit-preset/)
  assert.match(panel, /item\.path === catalog\.activePresetPath[\s\S]*rpc\("selectPreset", \{ path: result\.resource\.path \}/)
  assert.match(panel, /item\.path === catalog\.activePresetPath[\s\S]*rpc\("selectPreset", \{ path: "" \}/)
  assert.doesNotMatch(panel, /选择条目|启用所选条目|停用预设条目/)
  assert.doesNotMatch(panel, /existingPlanForPreset|setEntryKeys|setRegexKeys/)
  assert.doesNotMatch(panel, /rpc\("extractBypassPlan"|rpc\("activateBypassPlan"/)
  assert.doesNotMatch(panel, /破限方案|导入破限|适配模型/)
  assert.doesNotMatch(panel, /importBypassPlan|exportBypassPlan|toggleBypassPlanEntry|toggleBypassPlanRegex/)
  assert.match(serverSource, /case 'selectPreset'/)
  assert.match(serverSource, /presetLibrary\.select\(args && args.path\)/)
  assert.match(serverSource, /runtimePresets\.fullSnapshot\(\)/)
  assert.match(serverSource, /case 'updatePresetRegex'/)
})

test('卡片模式预加载人物卡、预设、世界书和剧本四个库', () => {
  assert.match(clientSource, /readyCardSession/)
  assert.match(clientSource, /props\.openCardLibraryTab\(readyCardSession\)/)
  assert.match(clientSource, /props\.openResourcesTab\(readyCardSession\)/)
  assert.match(clientSource, /props\.openPresetLibraryTab\(readyCardSession\)/)
  assert.match(clientSource, /props\.openWorldBookLibraryTab\(readyCardSession\)/)
  assert.doesNotMatch(clientSource, /openBoundaryLibraryTab/)
  assert.ok(clientSource.indexOf('props.openCardLibraryTab(readyCardSession)') < clientSource.indexOf('props.openResourcesTab(readyCardSession)'))
  assert.match(clientSource, /openCardLibraryTab: function \(sessionId\) \{ ctx\.betterSidebar\.openTab\(\{ type: "dsh-tavern:cards" \}/)
  assert.match(clientSource, /ctx\.betterSidebar\.updateTab\("dsh-tavern:cards", \{ meta: null \}\)/)
  assert.match(clientSource, /registerTab\(\{\s*id: "dsh-tavern:resources"/)
  assert.match(clientSource, /id: "dsh-tavern:resources",\s*title: "剧本库"/)
  assert.match(clientSource, /id: "dsh-tavern:worldbooks",\s*title: "世界书库"/)
  assert.match(clientSource, /function reconcileLibraryTabTitles\(\)/)
  assert.match(clientSource, /"dsh-tavern:resources": "剧本库"/)
  assert.match(clientSource, /subscribeState\(reconcileLibraryTabTitles\)/)
  assert.match(clientSource, /openTab\(\{ type: "dsh-tavern:resources" \}/)
  assert.doesNotMatch(clientSource, /openTab\(\{ type: "editor", id: "dsh-tavern:files"/)
  assert.match(clientSource, /group\("剧本", "source", resources\.resources/)
  assert.doesNotMatch(clientSource, /group\("素材", "source"/)
  assert.doesNotMatch(clientSource, /group\("剧本", "script"/)
  assert.match(clientSource, /kind === "worldbook".*tavern-worldbook:/)
  assert.match(clientSource, /: "@\\\"" \+ safePath \+ "\\\""/)
  assert.match(clientCss, /body\.dsh-tavern-shell-active \[data-ref-chip="file"\].*max-width: calc\(100% - 4px\).*text-overflow: ellipsis/s)
  assert.match(clientCss, /\.dsh-tavern-candidate-question \{ max-width: 680px; \}/)
  assert.match(clientSource, /rpc\("importSource"/)
  assert.match(clientSource, /已绑定：/)
  assert.match(clientSource, /未绑定/)
  assert.match(clientSource, /rpc\("getResource", \{ path: item\.path \}/)
  assert.match(clientSource, /"← 返回剧本库"/)
  assert.match(clientSource, /setOpenedScript\(null\)/)
  assert.doesNotMatch(clientSource, /props\.openResource\(item\.previewPath, label\)/)
  assert.match(clientSource, /function parseTextResourceFile/)
  assert.match(clientSource, /\.txt,\.md,\.json,\.epub/)
  assert.match(clientSource, /application\/epub\+zip/)
})

test('剧本库可以把未绑定剧本绑定给未绑定人物卡，并可直接解绑', () => {
  const library = between(clientSource, 'function TavernResourcesTab', 'function register(input)')

  assert.match(library, /setCards\(all\[0\] && all\[0\]\.cards \|\| \[\]\)/)
  assert.doesNotMatch(library, /rpc\("listCards"/)
  assert.match(library, /card\.script == null/)
  assert.match(library, /rpc\("bindScript", \{ cardPath: cardPath, path: item\.path \}/)
  assert.match(library, /rpc\("deleteScript", \{ cardPath: boundCard\.path \}/)
  assert.match(library, /"绑定人物卡"/)
  assert.match(library, /"解绑"/)
})

test('人物卡库可以查看详情，并在当前卡片对话中引用人物卡', () => {
  const library = between(clientSource, 'function CardLibraryTab', 'function CardFieldsPanel')

  assert.match(library, /loadCard\(item\.path\)/)
  assert.match(library, /setLoading\(true\)/)
  assert.match(library, /rpcWithTimeout\("getCard", \{ path: path \}\)/)
  assert.match(library, /"重新读取"/)
  assert.match(library, /window\.addEventListener\("focus", onActivate\)/)
  assert.match(library, /在对话中引用/)
  assert.match(library, /props\.appendMention\(item\.path, item\.name\)/)
  assert.match(clientSource, /在对话中引用/)
  assert.match(clientSource, /requestedPath/)
  assert.match(clientSource, /loadCard\(requestedPath\)/)
})

test('Android 人物卡导入默认使用下载目录适配层，同时保留系统文件选择器', () => {
  assert.match(clientSource, /function MobileCardImportButton/)
  assert.match(clientSource, /rpcWithTimeout\("listMobileCardImports", \{\}\)/)
  assert.match(clientSource, /rpc\("importMobileCard", \{ id: file\.id \}\)/)
  assert.match(clientSource, /"从手机下载目录导入"/)
  assert.match(clientSource, /"使用系统文件选择器"/)
  assert.match(clientSource, /访问所有文件/)
  assert.match(serverSource, /case 'listMobileCardImports'/)
  assert.match(serverSource, /case 'importMobileCard'/)
})

test('隐藏的人物卡库不会刷新或上报迟到的读取错误', () => {
  const library = between(clientSource, 'function CardLibraryTab', 'function CardFieldsPanel')

  assert.match(library, /const visibleRef = React\.useRef\(Boolean\(props\.visible\)\)/)
  assert.match(library, /visibleRef\.current = Boolean\(props\.visible\)/)
  assert.match(library, /if \(!props\.visible\) return/)
  assert.match(library, /if \(visibleRef\.current\) setError\(String\(err && err\.message \|\| err\)\)/)
  assert.match(library, /\[selectedPath, props\.visible\]/)
  assert.match(library, /if \(props\.visible && requestedPath && requestedPath !== selectedPath\)/)
})

test('人物卡目录只读取卡片名称和剧本绑定，不加载或切分完整剧本', () => {
  const listing = between(serverSource, 'async function listCards()', 'async function getCardOpenings')
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')

  assert.match(listing, /fileResources\.scriptBindingsForCards\(cardPaths\)/)
  assert.match(listing, /fileResources\.hasCardImage\(cardPath\)/)
  assert.match(listing, /workspace\.meta\.importedAt/)
  assert.match(listing, /orderCardsByNewestImport\(cards\)/)
  assert.match(listing, /hasImage/)
  assert.doesNotMatch(listing, /readScript|splitNovelText|sourceChars|chunkCount/)
  assert.match(sidebar, /"剧本：" \+ card\.script\.title/)
  assert.doesNotMatch(sidebar, /card\.script\.chunkCount/)
})

test('PNG 人物卡在游玩选择器和人物卡库展示原版封面，JSON 卡不生成占位图', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const library = between(clientSource, 'function CardLibraryTab', 'function CardFieldsPanel')

  assert.match(serverSource, /pathname === '\/api\/dsh-tavern\/card-image'/)
  assert.match(serverSource, /fileResources\.readCardImage\(query\.get\('path'\)\)/)
  assert.match(sidebar, /function TavernCardListContent/)
  assert.match(sidebar, /card\.hasImage \? " with-image" : ""/)
  assert.match(sidebar, /TavernCardListContent/)
  assert.match(library, /function TavernCardListContent/)
  assert.match(library, /item\.hasImage \? " with-image" : ""/)
  assert.doesNotMatch(clientSource, /人物卡默认头像|card-placeholder/)
})

test('已迁移的人物卡读取时不会再次加载原版并执行迁移', () => {
  const reader = between(serverSource, 'async function readCardWorkspace', 'async function readCard(cardPath)')

  assert.match(reader, /const existing = await fileResources\.readCard\(normalized\)/)
  assert.match(reader, /if \(cardPreparation\.isWorkspace\(existing\)\) return existing/)
  assert.match(reader, /return await fileResources\.ensureCardWorkspace/)
})

test('人物卡导出读取当前绑定世界书并只写入导出副本', () => {
  const exporter = between(serverSource, "case 'exportCard':", "case 'addGuide':")

  assert.match(exporter, /worldBooks\.characterBookForCard\(cardPath\)/)
  assert.match(exporter, /cardPreparation\.present\(\{ card: workspace, as: 'sillytavern-v3', characterBook \}\)/)
})

test('人物卡 Agent 保存后重新读取已打开的详情，未变化时不重置表单', () => {
  const library = between(clientSource, 'function CardLibraryTab', 'function CardFieldsPanel')
  const listener = between(library, 'function onData(event)', 'window.addEventListener("dsh-tavern-data-changed"')

  assert.match(listener, /loadCard\(selectedPath\)/)
  assert.match(library, /setCard\(function \(current\)/)
  assert.match(library, /JSON\.stringify\(current\) === JSON\.stringify\(next\) \? current : next/)
})

test('删除对话时把缺失 Session 视为已经归档，并继续清理 Tavern 对话', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const deletion = between(sidebar, 'async function deleteConversation', 'async function exportCard')

  assert.match(sidebar, /function isMissingSessionArchiveError\(error\)/)
  assert.match(deletion, /catch \(archiveError\)/)
  assert.match(deletion, /if \(!isMissingSessionArchiveError\(archiveError\)\) throw archiveError/)
  assert.ok(deletion.indexOf('props.archiveSession(item.sessionId)') < deletion.indexOf('call("deleteChat", { chatId: item.chatId })'))
  assert.match(deletion, /props\.sessions\.clear\(\)/)
})

test('Session 顶栏工具区可以把服务端投影后的纯对话下载为 TXT', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
  const exporter = between(clientSource, 'function TavernConversationExportAction', 'function TavernPlayerNameAction')

  assert.match(serverSource, /case 'exportConversation': return await exportConversation/)
  assert.match(exporter, /rpc\("getSession", \{\}, props\.sessionId\)/)
  assert.match(exporter, /rpc\("exportConversation", \{ title: summary && summary\.displayTitle \|\| "" \}, props\.sessionId\)/)
  assert.match(exporter, /text\/plain;charset=utf-8/)
  assert.match(exporter, /new Blob\(\["\\uFEFF", result\.text\]/)
  assert.match(exporter, /"纯对话 TXT ↓"/)
  assert.match(clientSource, /slots\.inject\("conversation\.session\.header\.utilities"/)
  assert.match(clientSource, /id: "dsh-tavern-conversation-export"/)
  assert.doesNotMatch(sidebar, /导出 TXT|exportConversation/)
})

test('游玩对话由服务端联合压缩，浏览器只发起一次操作', () => {
  assert.match(clientSource, /rpc\("runCompaction", \{\}, props.sessionId\)/)
  assert.match(clientSource, /operation\.foreground\.message/)
  assert.match(clientSource, /operation\.background\.message/)
  assert.doesNotMatch(clientSource, /rpc\("prepareCompaction"/)
})

test('人物卡库通过列表进入详情，世界书编辑跳转到独立世界书库', () => {
  assert.match(clientSource, /id: "dsh-tavern:cards",\s*title: "人物卡库"/)
  assert.match(clientSource, /function CardLibraryTab/)
  assert.match(clientSource, /rpcWithTimeout\("getCard", \{ path: path \}\)/)
  assert.match(clientSource, /"基本信息"/)
  assert.match(clientSource, /"选择已有剧本"/)
  assert.match(clientSource, /call\("bindScript"/)
  assert.match(clientSource, /"导入新剧本并绑定"/)
  assert.match(serverSource, /Object\.assign\(\{\}, info, \{ path: script\.path \}\)/)
  assert.match(clientSource, /className: "dsh-tavern-script-hero"/)
  assert.match(clientSource, /h\("details", \{ className: "dsh-tavern-script-hero", onToggle:/)
  assert.match(clientSource, /script \? \("剧本模式 · " \+ script\.title\) : "剧本模式 · 未绑定"/)
  assert.match(clientSource, /绑定剧本后，新开的游玩对话会自动进入剧本模式/)
  assert.match(clientSource, /更换或解绑会影响所有使用这张人物卡的剧本对话/)
  assert.match(clientSource, /"世界书 · " \+ boundWorldBooks\.length/)
  assert.match(clientSource, /const boundWorldBooks =/)
  assert.doesNotMatch(clientSource, /hasWorldBookBinding \? null : h\("select"/)
  assert.match(clientSource, /"＋ 新增绑定"/)
  assert.match(clientSource, /dsh-tavern-worldbook-bound/)
  assert.match(clientSource, /props\.onOpenWorldBook\(book\.source\)/)
  assert.match(clientSource, /worldBookSource: source/)
  assert.match(clientSource, /"重命名文件"/)
  assert.match(clientSource, /"导出"/)
  assert.match(clientSource, /"删除"/)
})

test('人物卡详情只在展开绑定面板后读取剧本和世界书全库', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernPlayerNameAction')
  const scriptBinding = between(panel, 'function loadScript()', 'function loadScriptCatalog()')
  const worldBookBinding = between(panel, 'function loadWorldBookBinding()', 'function loadWorldBookCatalog(force)')

  assert.doesNotMatch(scriptBinding, /listResources/)
  assert.doesNotMatch(worldBookBinding, /listWorldBooks/)
  assert.match(panel, /onToggle: function \(event\) \{ if \(event\.currentTarget\.open\) loadScriptCatalog\(\); \}/)
  assert.match(panel, /onToggle: function \(event\) \{ if \(event\.currentTarget\.open\) loadWorldBookCatalog\(\); \}/)
})

test('人物卡绑定面板在世界书变化后刷新已打开的目录', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernPlayerNameAction')

  assert.match(panel, /const worldBookDetailsRef = React\.useRef\(null\)/)
  assert.match(panel, /window\.addEventListener\("dsh-tavern-data-changed", onWorldBookDataChanged\)/)
  assert.match(panel, /tavernDataChangeAffects\(event, \["worldbooks", "cards"\]\)/)
  assert.match(panel, /worldBookDetailsRef\.current && worldBookDetailsRef\.current\.open/)
  assert.match(panel, /loadWorldBookCatalog\(true\)/)
})

test('人物卡绑定目录超时后可在原位置重新读取', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernPlayerNameAction')
  const catalogLoader = between(panel, 'function loadWorldBookCatalog(force)', 'React.useEffect(function ()')

  assert.match(catalogLoader, /rpcWithTimeout\("listWorldBooks", \{\}\)/)
  assert.match(panel, /"重新读取"/)
  assert.match(panel, /onClick: function \(\) \{ loadWorldBookCatalog\(true\); \}/)
})

test('人物卡全部字段合并在默认展开的基本信息中，并位于世界书上方', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernStatusPanel')
  const basic = panel.indexOf('h("summary", null, "基本信息")')
  const alternateGreetings = panel.indexOf('F("alternate_greetings"')
  const creatorNotes = panel.indexOf('F("creator_notes"')
  const worldBook = panel.indexOf('h("summary", null, "世界书 · "')

  assert.ok(basic >= 0)
  assert.ok(alternateGreetings > basic)
  assert.ok(creatorNotes > alternateGreetings)
  assert.ok(worldBook > creatorNotes)
  assert.doesNotMatch(panel, /h\("summary", null, "高级字段"\)/)
})

test('人物卡详情只提交用户实际改动，避免投影往返覆盖完整 raw', () => {
  const panel = between(clientSource, 'function CardFieldsPanel', 'function TavernStatusPanel')
  assert.match(panel, /const baseline = \{/)
  assert.match(panel, /JSON\.stringify\(next\[key\]\) !== JSON\.stringify\(baseline\[key\]\)/)
  assert.match(panel, /call\("updateCard", \{ path: cardPath, patch: patch \}\)/)
})

test('人物卡稳定前缀统一交给快照模块管理，宿主只接线', () => {
  assert.match(serverSource, /const playCardSnapshots = createPlayCardSnapshots\(/)
  assert.match(serverSource, /const ensurePlayCardSnapshot = playCardSnapshots\.ensure/)
  assert.doesNotMatch(serverSource, /cardContextSnapshotVersion = 5/)
})

test('世界书库统一编辑独立世界书与人物卡内置世界书', () => {
  const cardPanel = between(clientSource, 'function CardFieldsPanel', 'function TavernStatusPanel')
  const library = between(clientSource, 'function WorldBookEditor', 'function CardLibraryTab')
  assert.doesNotMatch(cardPanel, /setBookEntry|addBookEntry|editingWorldBookKey/)
  assert.match(cardPanel, /尚未绑定世界书/)
  assert.match(library, /function WorldBookLibraryTab/)
  assert.match(library, /group\("独立世界书"/)
  assert.match(library, /group\("人物卡内置世界书"/)
  assert.match(library, /rpc\("importWorldBook"/)
  assert.match(library, /rpc\("updateWorldBook"/)
  assert.match(library, /const \[catalog, setCatalog\] = React\.useState\(null\)/)
  assert.match(library, /rpcWithTimeout\("listWorldBooks"/)
  assert.match(library, /rpcWithTimeout\("getWorldBookAssociations"/)
  assert.match(library, /"绑定人物卡"/)
  assert.match(library, /多本世界书可能相互冲突，引发异常/)
  assert.match(library, /rpc\("bindWorldBook"/)
  assert.match(library, /rpc\("unbindWorldBook"/)
  assert.match(library, /"正在读取世界书…"/)
  assert.match(library, /"重新读取"/)
  assert.match(clientSource, /function worldBookCatalogDiagnostic\(result\)/)
  assert.match(cardPanel, /setWorldBookCatalogWarning\(worldBookCatalogDiagnostic\(result\)\)/)
  assert.match(library, /setCatalogWarning\(worldBookCatalogDiagnostic\(result\)\)/)
  assert.match(library, /createWorldBookLibraryRefreshModule/)
  assert.doesNotMatch(library, /window\.addEventListener\("focus"/)
  assert.doesNotMatch(library, /document\.addEventListener\("visibilitychange"/)
  assert.match(library, /未知字段与 extensions 会原样保留/)
})

test('资料库读取 RPC 有超时收尾，不会永久停留在加载状态', () => {
  const timeout = between(clientSource, 'function rpcWithTimeout', 'function createLiveTavernViewModule')

  assert.match(timeout, /new AbortController\(\)/)
  assert.doesNotMatch(timeout, /withConnectionSlot/)
  assert.match(timeout, /window\.setTimeout/)
  assert.match(timeout, /读取超时，请重新读取/)
  assert.match(timeout, /window\.clearTimeout/)
})

test('游戏准备预热与正式启动不再操纵通知连接槽', () => {
  const sidebar = between(clientSource, 'function TavernSidebar', 'const tavernShellFeature = createTavernShellFeatureModule()')
  const assistantRenderer = between(clientSource, 'function createTavernAssistantRendererFeatureModule', 'function createTavernShellFeatureModule')

  assert.match(sidebar, /call\("preparePlayStart"\)/)
  assert.match(sidebar, /return call\("startChat"/)
  assert.doesNotMatch(sidebar, /withConnectionSlot/)
  assert.match(sidebar, /tavernSessionTransition\.begin\(\{ projection: transitionOpening && transitionOpening\.projection/)
  assert.match(sidebar, /busy && selectedOpening[\s\S]*renderTavernProjection\(selectedOpening\.projection/)
  assert.match(sidebar, /busy \? h\("div", \{ className: "dsh-tavern-session-switching", role: "status" \}, "正在完成游戏初始化…"\)/)
  assert.match(assistantRenderer, /renderTavernProjection\(sessionTransitioning\.projection/)
  assert.match(assistantRenderer, /正在完成游戏初始化/)
  assert.match(serverSource, /case 'preparePlayStart':[\s\S]*await runtimePresets\.prepareFullSnapshot\(\)/)
})

test('有效的世界书匹配设置在兼容字段之外，兼容字段默认折叠', () => {
  const editor = between(clientSource, 'function WorldBookEditor', 'function WorldBookLibraryTab')
  const compatibility = editor.indexOf('h("details", null, h("summary", null, "兼容字段")')

  assert.ok(compatibility >= 0)
  for (const label of ['"二级触发词"', '"启用"', '"使用二级条件"', '"区分大小写"', '"整词匹配"']) {
    assert.ok(editor.indexOf(label) >= 0 && editor.indexOf(label) < compatibility, label)
  }
  for (const label of ['"注入位置"', '"深度"', '"概率 %"', '"向量候选"', '"不被递归触发"']) {
    assert.ok(editor.indexOf(label) > compatibility, label)
  }
  assert.doesNotMatch(editor.slice(compatibility, compatibility + 80), /open:/)
})

test('世界书条目默认只显示标题，新建条目初始展开', () => {
  const editor = between(clientSource, 'function WorldBookEditor', 'function WorldBookLibraryTab')
  const row = between(editor, 'function entryRow', 'return h("div", { className: "dsh-tavern-library" }')

  assert.match(row, /return h\("details", \{ key: entry\.ref, className: "dsh-tavern-worldbook-entry", defaultOpen: String\(entry\.ref\)\.startsWith\("new:"\) \}/)
  assert.match(row, /h\("summary", \{ className: "dsh-tavern-worldbook-entry-head" \}, entry\.comment \|\| entry\.title \|\| "未命名条目"\)/)
  assert.ok(row.indexOf('dsh-tavern-worldbook-entry-body') < row.indexOf('"标题 / 备注"'))
  assert.ok(row.indexOf('dsh-tavern-worldbook-entry-body') < row.indexOf('"内容"'))
})

test('世界书条目删除位于展开区底部并要求二次确认', () => {
  const editor = between(clientSource, 'function WorldBookEditor', 'function WorldBookLibraryTab')
  const row = between(editor, 'function entryRow', 'return h("div", { className: "dsh-tavern-library" }')

  assert.match(editor, /window\.confirm\(/)
  assert.match(editor, /"删除世界书条目“" \+ title/)
  assert.match(editor, /保存世界书后才会正式删除/)
  assert.match(row, /className: "dsh-tavern-worldbook-danger-zone"/)
  assert.match(row, /"删除条目"/)
  assert.ok(row.indexOf('"兼容字段"') < row.indexOf('dsh-tavern-worldbook-danger-zone'))
})

test('酒馆状态页等待会话绑定就绪后自动刷新', () => {
  const statusTab = between(clientSource, 'function TavernStatusTab', 'const candidatePanel')
  const statusPanel = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')

  assert.match(statusTab, /props\.sessions\.list\.subscribe/)
  assert.match(statusTab, /props\.sessions\.binding\(props\.sessionId\)/)
  assert.match(statusPanel, /useLiveTavernView\(props\.sessionId, stateKey\)/)
  assert.match(statusPanel, /loadState = liveState\.phase/)
  assert.doesNotMatch(statusPanel, /rpc\("getSession"/)
  assert.match(statusPanel, /正在重新连接酒馆状态/)
  assert.match(clientSource, /isTerminalError: isMissingTavernCardError/)
  assert.match(statusPanel, /setError\(missingCard \? "" : \(liveState\.error \|\| ""\)\)/)
  assert.match(statusPanel, /人物卡已删除，酒馆状态不可用；已有对话仍可查看。/)
  assert.match(statusPanel, /loadState === "retrying" \|\| missingCard/)
  assert.match(statusPanel, /重新加载/)
})

test('人物卡持久状态栏由酒馆状态面板承载，不再覆盖对话正文', () => {
	const statusPanel = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
	assert.match(statusPanel, /TavernPersistentStatusRuntime/)
	assert.doesNotMatch(clientSource, /dsh-tavern-persistent-status-view/)
})

test('本局人物设计档案以只读折叠项进入酒馆状态并随实时视图刷新', () => {
	const statusPanel = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
	const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')
	assert.match(view, /characterDesigns: projectCharacterDesignDocument\(chat\.characterDesignDocument\)/)
	assert.match(statusPanel, /"人物设计档案（"/)
	assert.match(statusPanel, /view\.characterDesigns\.characters\.map/)
	assert.match(statusPanel, /h\("details", \{ key: character\.name \|\| index, className: "dsh-tavern-character-design" \}/)
	assert.match(statusPanel, /后台发现重要人物需要补全设计后，档案会自动出现在这里。/)
	assert.doesNotMatch(statusPanel, /deleteCharacterDesign|saveCharacterDesign|编辑人物设计/)
})

test('酒馆状态只服务游玩模式，卡片工作台面板暂不复用该侧栏', () => {
  const status = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
  const view = between(serverSource, 'async function view(chat, card)', 'function replyProjectionsOf')
  assert.match(status, /if \(view\.mode === "card"\) return null;/)
  assert.match(view, /worldBookError: chat\.worldBookError \|\| null/)
  assert.match(status, /世界书召回失败：/)
})

test('酒馆状态页不展示人物卡脚本按钮和内部兼容诊断', () => {
	const panel = between(clientSource, 'function TavernStatusPanel', 'function TavernStatusTab')
	const runtime = between(clientSource, 'function createTavernHelperScriptRuntime', 'function createTavernScriptExecutionModule')
	assert.doesNotMatch(panel, /人物卡脚本按钮/)
	assert.doesNotMatch(panel, /人物卡脚本兼容状态/)
	assert.doesNotMatch(panel, /tavernHelperScriptDiagnostics/)
	assert.doesNotMatch(panel, /tavernScriptExecutionModule\.triggerButton/)
	assert.match(clientSource, /return runtime\.triggerButton\(scriptId, name\)/)
	assert.match(runtime, /buttonEvent\(scriptId, name\)/)
	assert.match(runtime, /dsh-tavern-helper-ui-open/)
})

test('人物卡 Helper 的世界书写入按资源串行，避免生命周期事件并发覆盖', () => {
	assert.match(scriptHostAdapterSource, /serializeWorldbook\(worldbookKey\(initial\.record\)/)
	assert.match(scriptHostAdapterSource, /previous\.catch\(function \(\) \{\}\)\.then\(work\)/)
	assert.match(scriptHostAdapterSource, /await options\.worldBooks\.update/)
})

test('Helper 写入携带生命周期版本，过期 iframe 不覆盖 Swipe 或回退后的状态', () => {
	const runtime = between(clientSource, 'function createTavernHelperScriptRuntime', 'function createTavernScriptExecutionModule')
	const frame = between(clientSource, 'function createTavernMessageFrameLifecycle', 'function TavernMessageFrame')
	assert.match(runtime, /expectedLifecycleRevision/)
	assert.match(frame, /expectedLifecycleRevision/)
	assert.match(scriptHostAdapterSource, /staleMutation/)
  assert.match(scriptHostAdapterSource, /DSH_TAVERN_CHAT_CONFLICT/)
})

test('人物卡 iframe 不因等价上下文或切换会话而重复启动', () => {
	const frame = between(clientSource, 'function TavernMessageFrame', 'function tavernProjectionForTurn')
	const renderer = between(clientSource, 'function createTavernAssistantRendererFeatureModule', 'function createTavernShellFeatureModule')
	const sidebar = between(clientSource, 'function TavernSidebar', 'function TavernResourcesTab')
	const capture = between(serverSource, 'async function captureDisplayRuntime', 'const tavernScriptHostAdapter')

	// Lifecycle/transport behavior is exercised through the production factory in
	// card-runtime-lifecycle and through the actual component in helper-context-refresh.
	assert.match(frame, /createTavernMessageFrameLifecycle\(frameProps\)/)
	assert.match(frame, /lifecycle\.start\(setState\)/)
	assert.match(frame, /lifecycle\.update\(frameProps\)/)
	assert.match(frame, /opacity: 0/)
	assert.match(frame, /IntersectionObserver/)
	assert.match(frame, /loading: "lazy"/)
	assert.match(renderer, /tavernSessionTransition\.subscribe/)
	assert.match(renderer, /latestProjectionTurn/)
	assert.match(renderer, /eagerFrame: storyTurn > 0 && storyTurn === latestProjectionTurn/)
	assert.match(renderer, /sessionTransitioning\.projection/)
	assert.match(renderer, /正在完成游戏初始化/)
	assert.match(sidebar, /tavernSessionTransition\.begin\(\{ projection:/)
	assert.match(sidebar, /setOpeningPicker\(null\)/)
	assert.match(capture, /sameDisplayRuntimeCapture/)
	assert.match(capture, /touchUpdatedAt: false/)
})

test('剧本预览只显示当前召回和后续块', () => {
  assert.match(clientSource, /index === 0 \? "当前召回" : "后续"/)
  assert.doesNotMatch(clientSource, /上一块（已召回）|当前待召回|scriptPreview\.previous/)
})

test('实验分支开放兼容入口并保留普通游玩与资源能力', () => {
	const player = between(clientSource, 'function TavernPlayerNameAction', 'function TavernStatusPanel')
	const shell = between(clientSource, 'function TavernSidebar', 'function register(input)')
	const action = between(clientSource, 'function CandidateAction', 'function CandidateDockActions')
	const coordination = between(clientSource, 'function coordinationView', 'function createTavernCoordinationEventModule')
	const preStep = between(serverSource, "ctx.on('agent/pre-step'", "ctx.on('llm/stream'")
	const llmStream = between(serverSource, "ctx.on('llm/stream'", "ctx.on('agent/turn-stopping'")
	const systemAssembly = between(serverSource, "ctx.on('system-prompt/assemble'", '// ---------- 模型可选工具 ----------')

	assert.match(shell, /const compatibilityAvailable = true/)
	assert.match(clientSource, /name: "settings\.section"/)
	assert.match(clientSource, /id: "dsh-tavern"/)
	assert.doesNotMatch(clientSource, /启用兼容模式（实验性）/)
	assert.doesNotMatch(clientSource, /受信任人物卡模式|SillyTavern 样式环境/)
	assert.match(clientSource, /sandbox: document\.trustedCardMode \? undefined : "allow-scripts"/)
	assert.match(clientSource, /if \(!trustedCardMode\) frame\.sandbox = "allow-scripts"/)
	assert.match(serverSource, /trustedCardMode/)
	assert.match(clientSource, /Boolean\(result && result\.active\) !== active/)
	assert.match(clientSource, /releaseTavernHelperRuntime/)
	assert.match(clientSource, /updateTavernSettings/)
	assert.doesNotMatch(shell, /onClick: function \(\) \{ switchPlayRequestMode\("sillytavern"\); \} \}, "兼容（实验性）"/)
	assert.match(shell, /item\.requestMode === "sillytavern" \? "sillytavern" : "dsh"\) === requestMode/)
	assert.match(shell, /item\.requestMode === "sillytavern" \? "sillytavern" : "dsh"\) === nextRequestMode/)
	assert.doesNotMatch(shell, /call\("setRequestMode", \{ sessionId: target\.sessionId/)
	assert.match(shell, /兼容对话|新开兼容对话/)
	assert.match(shell, /if \(!target\) \{ props\.sessions\.clear\(\); openPicker\(\); return; \}/)
	assert.doesNotMatch(shell, /\}, "兼容（实验性）"\)/)
	assert.match(coordination, /requestMode: sync\.requestMode === "sillytavern"/)
	assert.match(action, /"重新生成候选项"[\s\S]*"重新生成正文"/)
	assert.doesNotMatch(action, /requestMode === "sillytavern"\) return/)
	assert.match(action, /rollbackViewState = useLiveTavernView\(props\.sessionId,[\s\S]*canRollback = rollbackViewState\.view && rollbackViewState\.view\.canRollback === true/)
	assert.match(clientSource, /function TavernMoreActions[\s\S]*React\.createElement\(TavernRollbackAction, props\)[\s\S]*React\.createElement\(TavernCompactionAction,/)
	assert.match(action, /liveTavernView\.invalidate\(props\.sessionId\)[\s\S]*tavernCoordination\.invalidate\(props\.sessionId\)/)
	assert.match(serverSource, /canRollback: hasRollbackMessages\(chat\.messages\)/)
	assert.doesNotMatch(player, /setRequestMode|请求：酒馆兼容/)
	assert.doesNotMatch(clientSource, /"请求模式".*"select"/s)
	assert.doesNotMatch(serverSource, /resolveDeveloperMode|DSH_TAVERN_DEV_MODE|仅在开发模式下可用/)
	assert.match(serverSource, /getTavernSettings/)
	assert.match(serverSource, /settings\.compatibilityMode && requestMode === 'sillytavern'/)
	assert.doesNotMatch(serverSource, /兼容模式已停用/)
	assert.match(preStep, /foregroundStrategies\.prepareStep/)
	assert.match(serverSource, /compileTurn: compileCompatibilityTurn/)
	assert.match(serverSource, /applySillyTavernStrictTools\(compiled\.messages/)
	assert.match(serverSource, /compiled\.trace\.postProcessing = 'strict_tools'/)
	assert.match(orchestrationStrategiesSource, /return \{ kind: 'enter', messages: payload\.messages \}/)
	assert.doesNotMatch(serverSource, /compatibilitySummaryMessage/)
	assert.doesNotMatch(llmStream, /options\.messages\s*=/)
	assert.match(llmStream, /foregroundStrategies\.projectRequest\(options, coordinates\)/)
	assert.match(orchestrationStrategiesSource, /isCompatibilityConversationRequest\(optionsValue, staged, coordinates\)/)
	assert.match(orchestrationStrategiesSource, /createEphemeralCompatibilityRequest\(optionsValue, staged\.messages\)/)
	assert.match(llmStream, /return ctx\.llm\.stream\(projectedRequest\)/)
	assert.match(serverSource, /turnOrchestrator\.beginCompatibility\(input\)/)
	assert.match(systemAssembly, /foregroundStrategies\.assembleSystemPrompt/)
	assert.match(orchestrationStrategiesSource, /assembly\.sections = \[\]/)
	assert.match(orchestrationStrategiesSource, /assembly\.contexts = \[\]/)
	assert.match(orchestrationStrategiesSource, /input\.chat\.webSearchEnabled === true/)
	assert.match(orchestrationStrategiesSource, /tool\.name === 'web_search'/)
	assert.doesNotMatch(serverSource, /酒馆兼容模式不运行 DSH 后台候选项/)
	assert.doesNotMatch(serverSource, /waitUntilSettled: async function \(chat\) \{[\s\S]*if \(chat\.requestMode === 'sillytavern'\) return/)
	assert.doesNotMatch(serverSource, /choiceChat\.requestMode !== 'sillytavern' && !await pullBackgroundCycle/)
	assert.doesNotMatch(clientSource, /后台变量结算与普通游玩共用同一链路，候选项可按需手动生成/)
})

test('右侧系统提示词面板编辑唯一一套提示词并支持整套导入导出', () => {
	const panel = between(clientSource, 'function SystemPromptSidebarTab', 'function createResourcesLibraryFeatureModule')
	assert.match(clientSource, /id: "dsh-tavern:system-prompts"/)
	assert.match(clientSource, /title: "系统提示词"/)
	assert.match(panel, /当前使用的唯一一套内置提示词/)
	assert.match(panel, /修改系统提示词可能导致正文生成异常、人物卡指令冲突、后台任务失败或输出格式失效/)
	assert.match(panel, /updateSystemPrompt/)
	assert.match(panel, /resetSystemPrompts/)
	assert.match(panel, /importSystemPrompts/)
	assert.match(panel, /exportSystemPrompts/)
	assert.match(panel, /dsh-tavern-system-prompt-head/)
	assert.match(panel, /dsh-tavern-system-prompt-top-actions/)
	assert.match(panel, /dsh-tavern-system-prompt-body/)
	assert.match(clientCss, /\.dsh-tavern-system-prompt-top-actions \{ display: flex; flex-wrap: wrap; gap: 8px 10px; margin-top: 10px; \}/)
	assert.match(clientCss, /\.dsh-tavern-preset-detail\.dsh-tavern-system-prompt-body \{ padding: 20px 24px 28px; \}/)
	assert.match(serverSource, /spec: 'dsh-tavern\.system-prompts'/)
	assert.match(serverSource, /createContextPlanner\(\{ prompt: runtimePrompt/)
	assert.match(serverSource, /prompt: runtimePrompt/)
})

test('普通游玩投影对话预设快照，兼容模式继续按 SillyTavern 结构编译', () => {
	const panel = between(clientSource, 'function createExternalPresetAndBypassPlanFeatureModule', 'function createWorldBookLibraryFeatureModule')
	const compile = between(serverSource, 'async function compileCompatibilityTurn', 'function compatibilityMessages')
	const preStep = between(serverSource, "ctx.on('agent/pre-step'", "ctx.on('llm/stream'")

	assert.match(panel, /selectPreset/)
	assert.doesNotMatch(panel, /extractBypassPlan|activateBypassPlan/)
	assert.doesNotMatch(panel, /toggleBypassPlanEntry|toggleBypassPlanRegex/)
	assert.doesNotMatch(serverSource, /compatibility-presets\.json|createCompatibilityPresetState/)
	assert.match(compile, /const snapshot = await resolveChatRuntimePreset\(chat\)/)
	assert.match(compile, /presetPath === '' \? createCleanCompatibilityPreset\(\) : snapshot\.compatibilityPreset/)
	assert.match(compile, /presetPath === '' \? \{\} : snapshot\.compatibilityPresetDocument/)
	assert.match(compile, /Array\.isArray\(snapshot && snapshot\.regexScripts\) \? snapshot\.regexScripts : \[\]/)
	assert.doesNotMatch(compile, /bypassPlans/)
	assert.match(serverSource, /return chat\.runtimePresetSnapshot && typeof chat\.runtimePresetSnapshot === 'object'/)
	assert.match(turnOrchestrationSource, /presetMiddleInstructions\(snapshot\)/)
	assert.match(orchestrationStrategiesSource, /scope: 'foreground'/)
	assert.match(serverSource, /persistCompiled: async function \(input\) \{[\s\S]*await updateChat\(input\.chat\.id,[\s\S]*source: 'compatibility\.compile'/)
	assert.match(serverSource, /resolvePreset: resolveChatRuntimePreset/)
	assert.match(serverSource, /foregroundFrameSessionAdapter\.append\(input\)/)
	assert.match(orchestrationStrategiesSource, /prepared\.frame\.userInput\.projectedText/)
})

test('Foreground Frame 使用无需 Web Crypto 接收者的 UUID 回调', () => {
	assert.match(serverSource, /createForegroundFrameSessionAdapter\(\{ id: randomUUID \}\)/)
	assert.doesNotMatch(serverSource, /createForegroundFrameSessionAdapter\(\{ id: crypto\.randomUUID \}\)/)
})

test('隔离 Helper iframe 可以只读加载已锁定的本机远程资源', () => {
	const handler = between(serverSource, "handler: async (req, res) => {", "function contentText(message)")
	assert.match(handler, /const readsCachedAsset = req\.method === 'GET' && cachedAssetMatch/)
	assert.match(handler, /const readsStaticAsset = req\.method === 'GET'/)
	assert.match(handler, /const localOrOpaqueOrigin =/)
	assert.match(handler, /if \(readsStaticAsset && !localOrOpaqueOrigin\)/)
	assert.match(handler, /if \(!readsCachedAsset && !readsStaticAsset && !readsOfficialMvu && !readsFullTemplate && !readsRuntimeAsset && !readsClientAsset && !sceneSameOrigin && typeof origin === 'string'/)
	assert.match(handler, /'Access-Control-Allow-Origin': '\*'/)
	assert.match(handler, /'Cross-Origin-Resource-Policy': 'cross-origin'/)
})

test('HTTP RPC 在启动恢复前注册，并等待运行时完成初始化', () => {
	const routeRegistration = serverSource.indexOf("ctx.effect(() => webServer.register({")
	const runtimeInitialization = serverSource.indexOf('await initializeRuntimeState()')
	const runtimeReady = serverSource.indexOf('settleRuntimeReadiness({ ok: true })')
	const historyRecovery = serverSource.indexOf('recoverRuntimeHistory(recoveredIndex).catch')
	const handler = between(serverSource, "handler: async (req, res) => {", "function contentText(message)")
	assert.notEqual(routeRegistration, -1)
	assert.notEqual(runtimeInitialization, -1)
	assert.notEqual(runtimeReady, -1)
	assert.notEqual(historyRecovery, -1)
	assert.ok(routeRegistration < runtimeInitialization)
	assert.ok(runtimeInitialization < runtimeReady)
	assert.ok(runtimeReady < historyRecovery)
	assert.match(handler, /const readiness = await runtimeReadiness/)
	assert.match(handler, /if \(!readiness\.ok\) throw readiness\.error/)
})

test('Tavern 用独立启动标识刷新旧插件前端，不复用 Session 恢复守卫', () => {
	const handler = between(serverSource, "handler: async (req, res) => {", "function contentText(message)")
	assert.match(handler, /pathname === '\/api\/dsh-tavern\/runtime-generation'/)
	assert.match(handler, /'Cache-Control': 'no-store, max-age=0'/)
	assert.match(handler, /JSON\.stringify\(\{ ok: true, runtimeGeneration \}\)/)
	assert.match(handler, /Object\.assign\(\{ ok: true \}, result, \{ runtimeGeneration \}\)/)
	assert.match(clientSource, /createTavernRuntimeGenerationMonitor/)
	assert.match(clientSource, /fetch\(script\.src, \{ cache: "reload" \}\)/)
	assert.match(clientSource, /fetch\("\/api\/dsh-tavern\/runtime-generation", \{ cache: "no-store" \}\)/)
	assert.doesNotMatch(clientSource, /dsh-tavern:runtime-generation:v1/)
	assert.doesNotMatch(clientSource, /dsh-tavern:reconnect-draft:v1/)
})

test('Helper 全部就绪后直接广播 CHAT_CHANGED，官方 MVU 自行完成开场初始化', () => {
	const module = between(clientSource, 'function createTavernScriptExecutionModule', 'function TavernScriptRuntime')
	// CHAT_CHANGED payload and lease behavior are exercised in card-runtime-lifecycle.test.mjs.
	assert.match(module, /onReady: function \(readySessionId\)/)
	assert.match(module, /signals\.subscribe\(sessionId, "runtime-work"/)
	assert.match(module, /"claimTavernScriptWork"/)
	assert.doesNotMatch(module, /schedulePoll|pollTavernHelperEvent|active \? 100 : 500/)
	assert.doesNotMatch(module, /initializeTavernMvuOpenings/)
})
